### ISSUE TITLE
Some solid metal doors can be shot through.

### ISSUE THREAD

**Issue by mjstahlberg** [UnvanquishedAssets/map-perseus_src.dpkdir#4]
At least all three doors adjacent to the canteen can be shot through. The two small doors can be shot through even through their solid metal parts, not just the grilled part where it would make a little sense. The one large door can be shot only through its middle, even though solid metal meets there.

This is problematic in particular because rocket pods can aim and fire through these doors. If the grilled part remains shoot-through, then it needs missile clip so that the rocket pod doesn't.

**Comment by cu-kai** [comment]
freem mentioned this on irc and I further investigated it. It would appear that the offending doors are using a nonsolid shader on some parts, see below: 
![door1 in radiant](https://media.discordapp.net/attachments/193638031478095872/817889702329188352/unknown.png)
![door1 ingame with medistation](https://media.discordapp.net/attachments/193638031478095872/817883040067616809/unknown.png)

Although this door is using nonsolid textures everywhere you can only shoot through the middle of the door which is a very strange bug:
![door2 in radiant](https://media.discordapp.net/attachments/193638031478095872/817888948872675338/unknown.png)

**Comment by illwieckz** [comment]
This is believed to be fixed for `perseus` map.
