### ISSUE TITLE
C8 black weird rendering

### ISSUE THREAD

**Issue by ghost** [UnvanquishedAssets/map-perseus_src.dpkdir#9]
![2023-04-09](https://user-images.githubusercontent.com/1316300/230784677-c2037a1b-a39a-498b-9259-464c092ff65f.png)
![2023-04-09_000](https://user-images.githubusercontent.com/1316300/230784678-1755d518-6e40-4ab4-b870-bfa650520639.png)
![2023-04-09_001](https://user-images.githubusercontent.com/1316300/230784680-0626aa97-e6aa-4755-b212-8827d2f54bf6.png)

Lines only appear at the correct distance.
I also suspect the black backgound is not intended: the images there are transparent, and this lacks details unlike the other stuff in this map.

**Comment by illwieckz** [comment]
Was a bug in the toolchain.
